### ISSUE TITLE
Impossible de trouver le matériel

### ISSUE THREAD

**Issue by jfh75** [syrhus/solax_inverter#4]
Bonjour,

J'ai copié le plugin dans le répertoire plugin, j'ai relancé domoticz, mais je ne trouve pas le matériel solax.
Y a t il autre chose à faire ?
Merci de votre aide

JFH

**Comment by Rudi1952** [comment]
I installed the plugin in my domoticz, but the strange thing is that it gives me the wrong data:
When i look into my devices i see the correct data:
![image](https://user-images.githubusercontent.com/35039914/115952099-8d984f00-a4e4-11eb-9aa6-e83c4ecdabd1.png)
Here it says that the proceeds sofar is 2500 Watts
But when i look in the Utils i see different values:
![image](https://user-images.githubusercontent.com/35039914/115952199-f089e600-a4e4-11eb-8c08-d79261727411.png)
Here i see the value that it (SOLAX - 1) produces now (916 Watts) and a total of -17900 Watts.
Is it possible that the totals for today and total all are produced here?
