### ISSUE TITLE
Negative totals upon update Domoticz 2022.2

### ISSUE THREAD

**Issue by jprinsen** [syrhus/solax_inverter#6]
After the update to Domoticz 2022.2, daily totals are treated differently - total of the day before is reflected negative and new productions are summed up (hence: early morning while solar production is going on, total starts negative and becomes only positive when total of day before is superseded). 
On a more separate note and *not* related to update 2022.2, could it (also) be that 'instant' and 'usage' data recordings are switched?

<img width="387" alt="afbeelding" src="https://user-images.githubusercontent.com/24796548/200266537-1c9906ff-69fe-4d0a-b205-a0819a3362d0.png">
<img width="1176" alt="afbeelding" src="https://user-images.githubusercontent.com/24796548/200271267-200b47a4-3127-4c8e-a244-01c6b07c26b0.png">

**Comment by syrhus** [comment]
Hi, I aware about that. I tried to log an issue on domoticz but some guys don't want to consider it as a bug as you have to switch the device "Energy read" property from "From device" to "computed".
![image](https://user-images.githubusercontent.com/34164789/200502820-75c2c48b-772a-4d24-99a1-74b53802cff8.png)

That is what I did and now datas look like right.

**Comment by jprinsen** [comment]
Thank you very much; much appreciated!
